name = "MPSDynamics"
uuid = "8fc8f346-e1eb-498f-94db-02ffe92d8134"
authors = ["angus-dunnett <angus.dunnett@gmail.com>", "Thibaut Lacroix <thibaut.lacroix@proton.me>"]
version = "1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Jacobi = "83f21c0b-4282-5fbc-9e3f-f6da3d2e584c"

[compat]
TensorOperations = "4.0.0"
